### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by r00bal** [MrRafalGlowacki/goit-react-hw-08-phonebook#3]
https://github.com/MrRafalGlowacki/goit-react-hw-08-phonebook/blob/e3932343128ea0d48d4bf5f603b9c931a9812cc6/src/components/AppBar/SearchAppBar.jsx#L67-L70

Nad i pod handlerem, można by dodać linie przerwy dla lepszej czytelności projektu

**Comment by MrRafalGlowacki** [comment]
done
